server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://192.168.10.250:3307/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.250:8848

  application:
    name: gulimall-coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
